### ISSUE TITLE
before filter for >= 0.10.0

### ISSUE THREAD

**Issue by kushkella** [ruby-grape/grape#898] opened 2015-01-16 08:49 UTC
As of 0.9.0 version of gem before filter was only called for the version block within which it was defined. But from 0.10.0 it is being called for all version blocks as long as we don't group them as a resource/group/namespace. e.g.

```ruby
class Test < Grape::API
  resource :foo do
    version 'v1', :using => :path do
      before do
        puts 'foo'
      end
      get '/' do
        # something
      end
    end

    version 'v1', :using => :path do
      before do
        puts 'bar'
      end
      get '/:id' do
        # something
      end
    end
  end
end
```

when using 0.9.0 when I request `GET /foo/1`, the resource will only log "bar". But with 0.10.0 it will log both "foo" and "bar" as long as both version blocks are not individually wrapped inside a blank namespace/resource/group etc.

It would be great if you could explain if this is the desired behavior. Thanks!

**Comment by dblock** [comment] 2015-01-16 12:02
Very interesting. If anything this *is* a regression and we should document it in UPGRADING.md - would appreciate a PR.

I am honestly not sure what we want here. The `version` block is not something that even has to be a block, it has scope for whatever follows it as well. I am inclined to say that this is what we want by design and the workaround is to use `namespace`. That said, I could easily argue the opposite.

Would love to hear what others have to say.

**Comment by kushkella** [comment] 2015-01-16 12:18
Sure, I will create a PR.

I don't really like using `version` without a block. It is easy to read version of a specific resource-method if it is wrapped inside a `version` block. I started off with using version the way you described, but since we have so many methods/paths listed under a resource, it gets cumbersome to track versions without wrapping them in a version block.

And we use path for versioning, so we can easily switch to namespace/group etc. But I think we should treat version as something similar to namespace. The only difference being that version can be specified in path, header etc.

**Comment by dblock** [comment] 2015-01-16 12:19
I think I agree. Lets treat it as a regression for now that we should be fixing, want to try to do that?

**Comment by kushkella** [comment] 2015-01-16 12:24
Sure, I'll give it a shot and keep you posted. Meanwhile I try that, I'll document this behavior and create a PR. Thanks!

**Comment by kushkella** [comment] 2015-01-18 16:57
If possible, please release a new version of Grape soon. I'll really appreciate that. Thanks!

**Comment by dblock** [comment] 2015-01-18 19:13
Will do.

**Comment by dblock** [comment] 2016-07-29 20:29
I believe this was fixed by https://github.com/ruby-grape/grape/pull/901, closing. Please reopen @kushkella if I misunderstood something.

**Closed by dblock** 2016-07-29 20:29 UTC
Labels: bug?
