### ISSUE TITLE
Params validations do not run for route_param

### ISSUE THREAD

**Issue by dapicester** [ruby-grape/grape#1278] opened 2016-02-16 09:12 UTC
Hi, I found that validations do not run for `route_param`, here is a minimal example:
```ruby
# file: route_param.ru

require 'grape'

class Bang < Grape::Validations::Base
  def validate_param!(attr_name, params)
    fail Grape::Exceptions::Validation, params: [@scope.full_name(attr_name)], message: 'bang'
  end
end

class RouteParam < Grape::API
  format :json
  default_format :json

  params do
    requires :name, type: String, bang: true
  end
  route_param :name do
    get do
      present :name, params[:name]
    end
  end
end

run RouteParam
```

Run with `rackup route_param.ru` and then `curl localhost:9292/foo`.
I expect a validation failed message, but instead I get `{"name":"foo"}`.

I am using version 0.14.0.

Updated: fix sample code typos

**Comment by dblock** [comment] 2016-02-16 13:38
Routes are a little special. Route parameters *are* required to match the route and that their format is driven by `requirements`. However route parameters end up being regular parameters inside the API call, so validations would theoretically apply. Can you check that it's the case for a plain api call (not with `route_param`?). If that's the case then this would be a bug.

**Comment by dapicester** [comment] 2016-02-17 02:37
It was a typo in my sample code. Now the sample works as expected but in the project I am working on it seems that validation is not run. Let me double check and try to reproduce the error. I will eventually close this if I cannot reproduce the error.

**Comment by dapicester** [comment] 2016-02-17 05:55
I reproduced the problem. It seems that validations do not run when using `mount` in a `route_param` block.

Here is a sample code:
```ruby
# file: route_param.rb

require 'grape'

class Bang < Grape::Validations::Base
  def validate_param!(attr_name, params)
    fail Grape::Exceptions::Validation, params: [@scope.full_name(attr_name)],
                                        message: 'Bang!'
  end
end

class Params < Grape::API
  get do
    { params: params }
  end
end

class RouteParam < Grape::API
  format :json
  default_format :json

  version 'v1', using: :path do
    params do
      requires :name, type: String, allow_blank: false, bang: true
    end
    route_param :name do
      get do
        { params: params }
      end
    end
  end

  version 'v2', using: :path do
    params do
      requires :name, type: String, allow_blank: false, bang: true
    end
    route_param :name do
      mount Params
    end
  end
end

run RouteParam
```

Here is the error:
```shell
$ curl localhost:9292/v1/foo
{"error":"name Bang!"}
```
This is correct because the validation always fails.

```shell
$ curl localhost:9292/v2/foo
{"params":{"name":"foo"}}
```
This is not correct because the validation didn't run.

**Comment by dblock** [comment] 2016-02-17 13:38
You should turn this into a minimal spec next.

**Comment by vanburg** [comment] 2016-05-29 20:05
```ruby
route_param :party_id, type: Integer do
  mount Tracks => 'tracks'
end

# generates parties/tracks/:party_id
```
That is really required feature (this is how I got here). Subscribing.

**Comment by dblock** [comment] 2016-05-29 21:42
Thanks @vanburg, looking forward to some PRs!

**Comment by Arkanain** [comment] 2016-06-15 13:38
Hi guys. Any news about this issue? Because it's really uncomfortable to use(in case of last example) constructions like declared(params).merge(party_id: params.party_id) inside mounted class instead of regular declared(params).

**Comment by Arkanain** [comment] 2016-06-15 14:46
you can close this issue because all needed changes is already in latest master.

**Comment by dblock** [comment] 2016-06-15 16:30
How was it fixed? What was the PR?

**Comment by dblock** [comment] 2016-06-15 16:33
Oh I see, this was resolved via https://github.com/ruby-grape/grape/pull/1422.

**Comment by dblock** [comment] 2016-06-15 16:33
@namusyaka you might want to double-check this issue in case I missed something

**Closed by dblock** 2016-06-15 16:33 UTC
Labels: confirmed bug

**Comment by Arkanain** [comment] 2016-06-15 17:28
I check some specs on my project and I find out that this functionality work little bit wrong with `declared` when we have several `route_param` in one namespace.
For example we have:
```ruby
class Artists
  namespace :artists do
    route_param :id, type: Integer do
      get do
        Artist.find(declared(params))
      end
    end
    route_param :artist_id, type: Integer do
      mount Compositions
    end
  end
end
```
In `Artist.find(declared(params))` code `declared(params)` should return us next hash { id: 1 }, but it return hash { id: 1, artist_id: nil }

**Comment by dblock** [comment] 2016-06-15 18:18
@Arkanain Reopen a new issue please with hopefully a spec? Thanks.

**Comment by namusyaka** [comment] 2016-06-15 18:43
@dblock Yeah, I'll be careful. Thanks.

@Arkanain Your case can be reproduced in my environment and it seems like a bug. I'm going to dig the problem before long.

**Comment by Arkanain** [comment] 2016-06-16 08:54
@dblock I will create new issue little bit later.
@namusyaka I find out where we have problem! Problem is in options for `route_param`. where I use `route_param :id` without `type: Integer` everything is ok. Maybe it's because in sources, as I understand, route_param is a 'sugar' for structure like:
```ruby
params do
  requires :id, type: Integer
end
namespace ':id' do
  # some endpoints
end
```
That's why when we have two `route_param` in one namespace we have this wrong behaviour.

**Comment by dblock** [comment] 2016-06-16 11:38
We do document the first behavior is legal, but I bet `params` is not being properly reset with each new `namespace` declaration. Looks like a bug, thanks for opening it @Arkanain, please.

**Comment by Arkanain** [comment] 2016-06-16 20:40
@dblock As I promise previously I create pull request with specs for issue about I told you. Also I find one more bug in `declared` behaviour. Everything is here - https://github.com/ruby-grape/grape/pull/1430
