### ISSUE TITLE
Can't mount same API in nested path

### ISSUE THREAD

**Issue by CikeyPlanet** [ruby-grape/grape#1639] opened 2017-05-24 04:00 UTC
**I tried `mount` method and seems if I mount same class, only the last one will be valid.**

A simple example, it's not production ready codes:

If I have models `House`, `Room` and `Alarm`.
* A house can have many rooms and many alarms. 
* A room belongs to a house and can have many alarms. 
* An alarm can belongs to a house or a room.

I create API::AlarmAPI to CRUD alarms or one alarm(omit the codes here), and mount it twice to API::AlarmAPI in different place.

```ruby
module API
  class HouseAPI < Grape::API
  
    resource :houses do
      route_param :hid do
        mount API::AlarmAPI

        desc 'get specific house',{
          :entity => API::Entities::House
        }
        get do
          present :success, true
          present :house, current_house, with: API::Entities::House
        end
        
        
        resource :rooms do
        	route_param :rid do
        	  mount API::AlarmAPI
        	  
        	  desc 'get specific room under specific house',{
	          :entity => API::Entities::Room
	        }
	        get do
	          present :success, true
	          present :room, current_room, with: API::Entities::Room
	        end
        	
        	end
        end
       
      end
    end
  end
end

```

Then I can only get `/houses/:hid/rooms/:rid/alarms`, but no `/houses/:hid/alarms`.

**Comment by dblock** [comment] 2017-05-24 19:53
This is a duplicate of https://github.com/ruby-grape/grape/issues/570 I am afraid. Nobody was able to implement a solution for that, maybe you will!

**Closed by dblock** 2017-05-24 19:53 UTC
