### ISSUE TITLE
Compatibility with grape-entity > 0.5.0

### ISSUE THREAD

**Issue by przbadu** [ruby-grape/grape#1350] opened 2016-04-06 04:42 UTC
I forked and clone `grape` and run test cases on `master` branch and I got these three failing specs:

``` ruby
Failures:

  1) Grape::API http_codes is used as presenter
     Failure/Error: expect(last_response.body).to eql({ code: 408, static: 'some static text' }.to_json)

       expected: "{\"code\":408,\"static\":\"some static text\"}"
            got: "{:code=>408, :static=>\"some static text\"}"

       (compared using eql?)
     # ./spec/grape/api_spec.rb:2045:in `block (3 levels) in <top (required)>'

  2) Grape::API http_codes presented with
     Failure/Error: expect(last_response.body).to eql({ code: 408, static: 'some static text' }.to_json)

       expected: "{\"code\":408,\"static\":\"some static text\"}"
            got: "{:code=>408, :static=>\"some static text\"}"

       (compared using eql?)
     # ./spec/grape/api_spec.rb:2056:in `block (3 levels) in <top (required)>'

  3) Grape::Middleware::Error with http code presents an error message
     Failure/Error: expect(last_response.body).to eq({ code: 200, static: 'static text' }.to_json)

       expected: "{\"code\":200,\"static\":\"static text\"}"
            got: "{:code=>200, :static=>\"static text\"}"

       (compared using ==)
     # ./spec/grape/middleware/error_spec.rb:75:in `block (3 levels) in <top (required)>'

Finished in 8.14 seconds (files took 4.18 seconds to load)
```

We are expecting `json` response but are actually getting `String of Hash`. May be all of them are related with `presenter` and I also try to fixed it, but couldn't figure out the solution.

**Comment by przbadu** [comment] 2016-04-06 04:49
I am on `ruby 2.2.3`

**Comment by dblock** [comment] 2016-04-06 11:07
I can confirm that. Looks like it was introduced by grape-entity 0.5.1, which is used in specs. It work with 0.5.0. I don't see anything immediately obvious in https://github.com/ruby-grape/grape-entity/blob/master/CHANGELOG.md, opened https://github.com/ruby-grape/grape-entity/issues/213. Needs to be tracked down.

**Comment by dblock** [comment] 2016-04-06 11:15
Introduced by https://github.com/ruby-grape/grape-entity/pull/204.

**Comment by wleeper** [comment] 2016-05-13 20:53
This also affects the generation of error messages that use an Entity model for generating the output.  This is due to the fact that it is expecting the `present` method to generate a hash but now with 0.5.1 it generates an object.

**Comment by avyy** [comment] 2016-07-04 20:42
Hi guys. Please take a look: ruby-grape/grape-entity#232
Grape specs are green now.

**Comment by avyy** [comment] 2016-09-21 11:40
@wleeper @przbadu can you check grape master specs with last grape-entity? Everything works fine for me. I think the issue is not actual anymore.

**Comment by dblock** [comment] 2017-01-14 14:45
Closing.

**Closed by dblock** 2017-01-14 14:45 UTC
Labels: confirmed bug
