### ISSUE TITLE
Communicate `#after` hook errors in Middleware

### ISSUE THREAD

**Issue by rngtng** [ruby-grape/grape#1265] opened 2016-02-01 16:14 UTC
As of https://github.com/ruby-grape/grape/pull/1240 the `#after` hook is called on middlewares even when exception is raised. This breaks middleware which assume `response`, (`@app_response`) is set. (e.g. [grape_logging](https://github.com/aserafin/grape_logging)). 

Firstly, any middleware should be migrated to handle this case, secondly grape should give a warning at least, to help debugging and prevent the application from hard failure.

See discussion at: https://github.com/ruby-grape/grape/pull/1240#issuecomment-177977684

**Comment by dblock** [comment] 2016-02-01 19:18
:+1:

**Comment by jpaas** [comment] 2016-02-12 14:46
I am also running into this issue. My logging middleware is unable to log the response in the after hook.

**Comment by gregormelhorn** [comment] 2016-02-19 12:18
I am currently trying to fix this issue. One thing I stumbled upon is that the formatter also uses error handling to communicate issues in the after callback.

Fortunately, from what I can see now, catch(:error) and rethrowing while swallowing any StandardError from the after callback would fix the issue - but it also alters the behaviour of the formatter. I am not sure if this should really be implemented I have to say.

I would vote for a setting to switch on and off the "rescue StandardError behaviour" in the after callback (while still keeping and rethrowing any explicitly thrown error). 

What do you think?

**Comment by gregormelhorn** [comment] 2016-02-19 12:44
The more I think about it, the more it would make  sense to add a backwards compatibility switch (do not run after callbacks on error) instead of magically catching exceptions...

**Comment by dblock** [comment] 2016-02-22 12:02
@gregormelhorn Maybe. That seems to undo the change we made, I'd rather not have both behaviors and issue a warning as described in this issue. But do try some code and show us what happens before/after.

**Comment by gregormelhorn** [comment] 2016-02-22 14:44
The changes mean that any StandardError thrown gets transformed into a warning.

It also means that catching standard exceptions inside formatters is not possible, so I removed the corresponding tests. After all, the code does not care if the issue is in the after callback of a logging middleware or the after callback of a formatter.

I am still not sure if making this fail hard with exceptions is not the better way - it will be very easy to miss coding errors.

**Comment by rngtng** [comment] 2016-02-22 15:03
Ok, true a hard fail makes sense, but for debugging reason It would help a lot to know that the error happened in middleware  so what about a warning  + re-raise the original error?

**Comment by gregormelhorn** [comment] 2016-02-22 15:33
ok, I changed it accordingly :+1:

**Comment by dblock** [comment] 2016-02-22 20:39
Closed via https://github.com/ruby-grape/grape/pull/1285.

**Comment by rngtng** [comment] 2016-02-22 20:39
nice, thx

**Closed by dblock** 2016-02-22 20:39 UTC
Labels: feature request
