### ISSUE TITLE
Expose API class to each HTTP method block via something like the described_class() method in rspec

### ISSUE THREAD

**Issue by azbshiri** [ruby-grape/grape#1501] opened 2016-10-02 06:07 UTC
Hey, is it possible to access to the API class using a method to prevent from adding namespace resolution operator to the beginning of the class?

#### Actual behavior
```
module API
  module V1
    class APIClass < Grape::API
      get do
        ::APIClass.do_something
      end
   end
  end
end
```

### Expected behavior
```
module API
  module V1
    class APIClass < Grape::API
      get do
        grape_class.do_something
      end
   end
  end
end
```

**Comment by dblock** [comment] 2016-10-03 18:29
Duplicate of https://github.com/ruby-grape/grape/issues/1500.

**Closed by dblock** 2016-10-03 18:29 UTC
