### ISSUE TITLE
Optional param of type integer throws error when not defined

### ISSUE THREAD

**Issue by atomless** [ruby-grape/grape#1523] opened 2016-11-18 17:46 UTC
When you define an integer type param like so:
```Ruby
params :optional_jpeg_quality do
    optional :jpeg_quality, :type => Integer, desc: 'The jpeg quality of the output image, from 0 to 100.'
end
```
Then an endpoint using that is requested without a value for that param, this error is thrown:
```Bash
ERROR: Error : no implicit conversion of Symbol into Integer - at API request path: /foo, no implicit conversion of Symbol into Integer
```
You can avoid this error if you set it to have a default value like so:
```Ruby
params :optional_jpeg_quality do
    optional :jpeg_quality, :type => Integer, desc: 'The jpeg quality of the output image, from 0 to 100.', default: 100
end
```
but even so, seems like a bug ?

**Comment by dblock** [comment] 2016-11-18 18:35
Looks like a bug.

**Comment by nbulaj** [comment] 2016-11-24 18:17
Hi @atomless. Could you please provide more info about the bug? Full stacktrace for example.

I try to reproduce it, but does not get an error (Grape 0.18) - only `nil` if parameter was not set and actual value in other cases.

```ruby
#...

params do
  optional :jpeg_quality, :type => Integer, desc: 'The jpeg quality of the output image, from 0 to 100.'
end

post :test do
  puts params[:jpeg_quality].inspect
  {}
end
```

**Comment by tony612** [comment] 2016-12-06 03:36
I have this problem too..

**Comment by dm1try** [comment] 2016-12-06 11:41
Seems it's related to https://github.com/ruby-grape/grape/pull/1512 and fixed in master.

**Comment by dblock** [comment] 2016-12-06 14:37
@atomless @tony612 Can you please check against HEAD?

**Comment by tony612** [comment] 2016-12-07 03:20
@dblock It works for HEAD!

**Comment by dblock** [comment] 2016-12-07 16:43
Thanks @tony612. Closing.

**Closed by dblock** 2016-12-07 16:43 UTC
Labels: bug?
