### ISSUE TITLE
Include params from route into declared

### ISSUE THREAD

**Issue by 23tux** [ruby-grape/grape#1107] opened 2015-08-17 17:18 UTC
Hi,

maybe I'm doing something wrong, but it seems, that when I have a route like this `/api/articles/:id` and I use `declared(params)` the `:id` from the route is filtered out. In my opinion the `:id` is also declared, even it's not inside the `params` block.

So, is there an option to include the params from the route?

**Comment by dblock** [comment] 2015-08-18 14:02
Well, if it's not declared it's not declared :) I think the best way is to declare it. We parse and process path parameters [here](https://github.com/ruby-grape/grape/blob/94f52e48ef0a81405671ae410fb09616ec510ef9/lib/grape/endpoint.rb#L136), you should track where that goes. I think I'd like a method called `path_params` in a route that returns them or something like that if it doesn't exist, so I'll leave this open as a feature request.

**Comment by magni-** [comment] 2021-11-12 05:56
This looks like a duplicate of https://github.com/ruby-grape/grape/issues/733 ?

**Comment by dblock** [comment] 2021-11-12 19:56
Yep! And an old one, closing.

**Closed by dblock** 2021-11-12 19:56 UTC
Labels: feature request
