### ISSUE TITLE
Case insensitive headers

### ISSUE THREAD

**Issue by Cyclic** [ruby-grape/grape#1880] opened 2019-04-27 12:33 UTC
Using Grape 1.2.3 and started experiencing this issue after upgrading. Ruby 4.6.2p47, Rails 4.2.11.1 I've found that headers get lowercased, except the first character 'X', when using RSpec tests so my lookups for the header key fails. For example, when a request is made through my app, the case is converted to "X-Auth-Token", but when access through RSpec the same header appears as "X-auth-token".

I understand that headers are case insensitive, but what is responsible for converting the header case in grape? Ideally, the case is either all caps, all lowercase, or camel case - or there is a method provided in grape to lookup header keys with case insensitive matching. I don't want to write a wrapper as stated here: https://www.ruby-forum.com/t/case-insensitive-hash/51767/2

I'm at a loss on how to best access headers so that they are case insensitive, so any help is appreciated.

Thanks in advance.

**Comment by dblock** [comment] 2019-04-27 14:15
Grape does not convert headers lowercase/uppercase AFAIK, there's certainly no such cde. I don't believe you/we should be doing it. Did you bring in another dependency that's doing this? What did you upgrade from and to and can you narrow it down to grape?

**Comment by Cyclic** [comment] 2019-04-27 21:22
Thank you for the prompt response, and I very much appreciate your insight. I suspect that it's either faraday, httparty, or net::http; although, I have not been able to track it down. I thought others might have experienced this and have a general solution that might prevent me from having to write a wrapper class, and I agree, this is not something we should have to handle. I'll need to see if any libraries that I've added are doing this, but it only appears when upgrading from grape <= 13 to >= 15 (I suspect), but maybe even 14. I'll need to try out other grape versions to find out (like testing 14 with other fixes that I had to put in place). It definitely only happens when I bump the grape version.

**Comment by dblock** [comment] 2019-04-29 01:06
Coming back from #1881, the `headers` helper was added in https://github.com/ruby-grape/grape/commit/f6f585ea6cc720e779a37f756b9e9cda4786dad2 and from day 1 it converted the headers case into pascal-case. That is by design and I was wrong about whatever I said above.

Let's find out where the headers such as `X-Auth-Token` become `X-auth-token`, because I would expect Grape to not do this. Do you think you can cook up a simple repro @Cyclic?

**Comment by dblock** [comment] 2019-04-29 01:07
I opened https://github.com/ruby-grape/grape/issues/1882 to document what we do to headers.

**Comment by Cyclic** [comment] 2019-04-29 23:20
I was able to reduce the project down to a minimal number of files to reproduce the header casing issue. 

Please find the repo here:
https://github.com/Cyclic/rocket.api

Just clone the repo, run bundle install; rake db:create;

Execute rspec on spec/api/v1/core/reproduce_spec.rb

You should notice that X-NL-Auth-Token is all caps going into the get request, and then gets lowercased if you breakpoint in user_helpers.rb line 4, after the call to the API is made.

Just as a reminder, removing the ! from k = k[5..-1].split('_').each(&:capitalize!).join('-') seems to work in some cases, but I have yet to figure out why it doesn't work in others.

Thanks in advance and drop me a note if you have any trouble reproducing.

**Comment by dblock** [comment] 2019-04-30 14:13
Having hard time running the spec. It complains about missing `GuestUser` for one.

A simple thought in the meantime, `X-NL-Auth-Token` is not the capitalization of the code above, it should be `X-Nl-Auth-Token`, with a lowercase `l`. Does that fix the problem?

**Comment by Cyclic** [comment] 2019-04-30 14:37
Not sure why, but now I'm getting missing endpoint. I commented out the GuestUser code. If you can get the endpoint loaded, you will see that the header becomes X-nl-auth-token ...

I updated the repo with the changes to see if it works. I'm still trying to get it to work (it was working last night), but after running bundle update this morning, the spec stopped working. Going to try to get the endpoint working again so you can repro, but see if you might be able to figure out why it says endpoint is missing - it's mounted.

Thanks!

**Comment by Cyclic** [comment] 2019-04-30 14:41
Very odd! I was able to set a breakpoint on line 4 of user_helpers, after running bundle update, the headers are the correct case. X-NL-Auth-Token is now in the headers. Going to keep trying to repro.

**Comment by dblock** [comment] 2019-04-30 14:52
@Cyclic Care to get this into a state where I can see an actual failing spec? The current spec fails with "no such endpoint" if I look at `last_response.body`. This isn't what you expect I imagine.

**Comment by dblock** [comment] 2019-04-30 15:04
I got this. The issue is that the header is coming in as `HTTP_X-NL-Auth-Token` and not `HTTP_X_NL_AUTH_TOKEN`. The third parameter in `Rack::Test::Methods` is a Rack ENV object, not actual headers. This is well explained [here](https://ryanbigg.com/2014/08/add-header-to-rack-test-request).

So you either need to send a header as in a Rack object, ie.

```ruby
  def authenticated_headers(user_auth_token)
    {'HTTP_USER_AGENT' => user_auth_token.name, 'HTTP_X_NL_AUTH_TOKEN' => user_auth_token.auth_token}
  end
```

and

```
get '/v2/core/reproduce', {}, authenticated_headers(user_auth_token)
```

Or as a header

```
header 'X-Nl-Auth-Token', 'token'
get '/v2/core/reproduce'
```

I'll close this, but feel free to tack on more questions!

**Closed by dblock** 2019-04-30 15:04 UTC
Labels: bug?

**Comment by dblock** [comment] 2019-04-30 15:06
@Cyclic would you give https://github.com/ruby-grape/grape/issues/1882 a try?

**Comment by Cyclic** [comment] 2019-04-30 15:20
> @Cyclic Now that the mystery is solved, would you maybe give #1882 a try?

Yes, thank you for the insights! I appreciate your patience and helping me resolve the issue. That article explains it perfectly, so I'll cite that and make it clear in the documentation. I had questions about why it was using the env, but could not find any specific mention of why env was used in the build_headers method. Thanks again!

**Comment by Cyclic** [comment] 2019-04-30 15:31
One last nagging issue, any idea why there is a missing endpoint error? The spec was working when I first created it.

**Comment by Cyclic** [comment] 2019-04-30 15:36
Ok, new issue. After changing all of the headers to HTTP_X-Nl-Auth-Token, checking on the other end after the call, I get Http-X-Nl-Auth-Token ... shouldn't the HTTP_ be removed as before? Sorry for the questions, but this will all go towards the documentation and want to make sure I understand what type of behavior to expect. I updated the repo again.

**Comment by dblock** [comment] 2019-04-30 16:06
HTTP_ is a prefix added into the Rack env. So either you specify the header as `X-Nl-Auth-Token` or put it into env as `HTTP_X_NL_AUTH_TOKEN`.

I can look at the endpoint error later, but my guess is that you're not mounting the API into Rails routes properly or under a different path.

**Comment by dblock** [comment] 2019-07-06 14:47
I wrote this up in https://code.dblock.org/2019/07/06/handling-of-http-headers-in-grape-rack-rails.html and added examples [here for Rack](https://github.com/ruby-grape/grape-on-rack/pull/18) and [here for Rails](https://github.com/ruby-grape/grape-on-rails/pull/9).
