### ISSUE TITLE
Content type

### ISSUE THREAD

**Issue by MeterSoft** [ruby-grape/grape#1379] opened 2016-04-28 05:39 UTC
Hi, when client send content type application/x-www-form-urlencoded grape incorrect parse params, it should by xml. How i can forse parse all content type as xml or something like this?

in api 
format :xml
default_format :xml

**Comment by dblock** [comment] 2016-04-28 13:14
That's by design. The fact that the API defaults to XML doesn't mean that you force it to think you have XML when the client tells it the data format is something else. This is just the default.

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.

**Closed by dblock** 2016-04-28 13:14 UTC
