### ISSUE TITLE
Memory usage bump after upgrading to the latest version

### ISSUE THREAD

**Issue by filipebarros** [ruby-grape/grape#1835] opened 2018-12-06 13:57 UTC
After upgrading to the latest version I've noticed the memory consumption keeps going up so I created a dummy application to check if the same happened with the previous version:

```
require 'grape'

class API < Grape::API
  get :heartbeat do
    'OK'
  end
end

run API
```

Here's the memory usage with both `1.2.1` version and `1.1.0` at the start of the process and after 1000 and 10000 calls:

| | 1.2.1 - 1000 | 1.1.0 - 1000 | 1.2.1 - 10000 | 1.1.0 - 10000 |
| --- | --- | --- | --- | --- |
| Start | 25.4Mb | 26.4Mb | 25.2Mb | 25.1Mb | 
| Finish | 45.0Mb | 29.0Mb | 198.5Mb | 29.7Mb |

Here's the script I used to run the API calls.

```
for run in {1..1000} do
  curl -s "http://localhost:9292/heartbeat"
done
```

**Comment by dblock** [comment] 2018-12-06 19:11
Let's debug this more thoroughly? 

Check out https://github.com/ruby-grape/grape/issues/665 where we debugged a memory leak successfully for next steps.

cc: @myxoh

**Comment by nijikon** [comment] 2018-12-06 20:15
We are experiencing this as well, reverting to `1.1.0` fixed this issue for us.

**Comment by myxoh** [comment] 2018-12-06 20:40
Interesting, I wouldn't have thought the changes I've implemented should have impacted the memory consumption other than ever so slightly at load time. I'll take a look into this somewhere between late today and early tomorrow

**Comment by myxoh** [comment] 2018-12-06 21:51
oh wow. I think I've found the issue. This is unique to mounting the API directly on Rack I believe. `call` and `call!` are being called on the base instance, and hence continously added ot the `setup` of the application.
I already have a fix in place that passes all specs. I'll be creating a PR in a minute now.

Thanks for realizing this!

**Comment by myxoh** [comment] 2018-12-06 22:11
As a colour note, on my local testing this fix puts the memory footprint of `1.2.2` in the same values as the `1.1.0` .

**Comment by dblock** [comment] 2018-12-06 22:23
@nijikon @filipebarros Please do try the code from https://github.com/ruby-grape/grape/pull/1836 and confirm whether the problem is fixed?

**Comment by myxoh** [comment] 2018-12-07 00:31
Also, benchmarking the time for 1,000 calls gives me similar results for both `1.1.0` and `master`

**Comment by dblock** [comment] 2018-12-07 01:58
Good. I say cut a release.

**Comment by filipebarros** [comment] 2018-12-07 10:46
Tested against `34610f56ef99dbc1d9bd1efd6fa564482020e7d2` and memory usage is steady around 29Mb for 10000 calls 👍

**Comment by myxoh** [comment] 2018-12-07 14:02
OK, I'll close this issue and will open another one for the release of 1.2.2

**Closed by myxoh** 2018-12-07 14:02 UTC
Labels: confirmed bug

**Comment by nijikon** [comment] 2018-12-13 18:01
@dblock `1.2.2` works for us, thanks!

**Comment by aceunreal** [comment] 2018-12-18 00:19
Thanks for the release 👍
