### ISSUE TITLE
Error message with Rspec mock is wrong when using grape

### ISSUE THREAD

**Issue by FlorianDoublet** [ruby-grape/grape#1897] opened 2019-07-23 14:02 UTC
Hi, I have a bug with Rspec and Grape, but I don't really know If I should post this ticket here or on Rspec.. ( So I also post this issue to https://github.com/rspec/rspec-mocks/issues/1284 )

I'm using :
Ruby version: 2.5.3 ( with jruby 9.2.7.0 )
rspec-mocks version: 3.8.1
grape version: 1.2.3

My problem is when I `expect` a method call with args on an object and that test fails because of the args, Rspec + Grape tell me that the call never happened.

But when I execute a dumb test without Grape ( a classic Rails controller may work fine too ) I have the message error I expect : 

	My method was expected to be called once with (x, y) args, but 
	My method was called once with (x).

I have a simple API with a dumb endpoint `fake_endpoint`
in order to reproduce the bug :

```
Module Fake  
  class Base < Grape::API  

	  version 'f1', using: :path  
	  
	  get 'fake_endpoint' do  
		  Toto.tata(true, false)  
		  { test: "fake_data"}  
	  end  
   end
 end
```

And here are my tests : 

```
  
RSpec.describe Fake::Base do  
  
  
	describe "test call" do  
  
		it "1" do  
		  expect(Toto).to receive(:tata).with(true).and_return(nil)  
	      get_json(url: "/f1/fake_endpoint")  
		end  
	  
		it "1 bis" do  
			expect(Toto).to receive(:tata).with(true).and_return(nil)  
			Toto.tata(true, false)  
	    end  
	end
 end
```

Result of the failing test `1` : 

```
RSpec::Mocks::MockExpectationError: (Toto (class)).tata(true)
    expected: 1 time with arguments: (true)
    received: 0 times

  0) Fake::Base test call 1
     Failure/Error: expect(Toto).to receive(:tata).with(true).and_return(nil)

       (Toto (class)).tata(true)
           expected: 1 time with arguments: (true)
           received: 0 times
     # ./spec/api/fake/fake_spec.rb:9:in `block in <main>'
```

Result of the failing test `1 bis` : 

```

RSpec::Mocks::MockExpectationError: #<Toto (class)> received :tata with unexpected arguments
  expected: (true)
       got: (true, false)
Diff:
@@ -1,2 +1,2 @@
-[true]
+[true, false]


  0) Fake::Base test call 1 bis
     Failure/Error: Toto.tata(true, false)

       #<Toto (class)> received :tata with unexpected arguments
         expected: (true)
              got: (true, false)
       Diff:
       @@ -1,2 +1,2 @@
       -[true]
       +[true, false]
     # ./spec/api/fake/fake_spec.rb:15:in `block in <main>'
```

Maybe it seems to be just a little bug, but in fact it's quite annoying and if the params are complex, we can't figure out what the cause of this failure is...

Thanks for your help.

**Comment by dblock** [comment] 2019-07-23 22:18
I'll take a look at this, cause it seems like an odd and potentially fun one :) Appreciate if you could put up a project with a repro on github to save us time?

**Comment by FlorianDoublet** [comment] 2019-07-24 09:20
I'm trying to reproduce it with a minimal jruby project, but I can't reproduce the bug for the moment and I don't figure out why ... :(

**Comment by FlorianDoublet** [comment] 2019-07-24 09:26
Moreover on my real project, I don't see this bug using `spies` instead of simple mock. 

So if I do 

```
it "1" do
    allow(Toto).to receive(:tata) 
    get_json(url: "/f1/fake_endpoint")  
    expect(Toto).to have_received(:tata).with(true).and_return(nil)  
end  
```

then my test fail with the good error message .. This is weird

**Comment by dblock** [comment] 2019-07-24 12:05
Double check that the grape and other gem versions are the same, just in case.

**Comment by dblock** [comment] 2019-07-24 12:06
Another idea is to switch `expect(Toto).to have_received` to `expect(Toto).to receive` before the API call. I have a suspicion that it might be memoizing something across tests.

**Comment by FlorianDoublet** [comment] 2019-07-24 14:32
> Another idea is to switch `expect(Toto).to have_received` to `expect(Toto).to receive` before the API call. I have a suspicion that it might be memoizing something across tests.

I don't really understand ? the version with `expect(Toto).to receive` before API call is the version with a bug, and setting a spy and set `expect(Toto).to have_received` after the API call is the solution I found to my issue ( since I still have the bug with `expect(Toto).to receive` )

**Comment by FlorianDoublet** [comment] 2019-07-24 14:36
> Double check that the grape and other gem versions are the same, just in case.

Unfortunately I can confirm that rspec gems, grape, rails, ruby and jruby versions are the same in my Gemfile.lock ..

**Comment by FlorianDoublet** [comment] 2019-07-24 14:49
And I just copy-paste my Gemfile and my Gemfile.lock from my old to the new one, with all my gems, but I still can't reproduce this bug

**Comment by dblock** [comment] 2019-07-24 22:40
> And I just copy-paste my Gemfile and my Gemfile.lock from my old to the new one, with all my gems, but I still can't reproduce this bug

Start deleting things from your project until it's no longer reproduced.

I am going to close this since this looks project-specific, but would love to either get a repro that I can use or prove that it's Grape's fault (in which case we can reopen).

**Closed by dblock** 2019-07-24 22:40 UTC
Labels: bug?

**Comment by FlorianDoublet** [comment] 2019-08-01 13:57
@dblock If you are still curious I finally find out what cause my issue, and how to reproduce it. Just check this commit : https://github.com/FlorianDoublet/grape-rspec-mock-issue/commit/68dfd4b20f68a7b232e83b0ce52790dfd5737c0f

But I still don't understand why it happend only inside a grape request test, and why it work fine with a spy..

**Comment by dblock** [comment] 2019-08-01 21:21
Well, at least you are narrowing it down :)

**Comment by FlorianDoublet** [comment] 2019-08-02 08:14
Yes, thanks for your time :)
