### ISSUE TITLE
Autoloading issues after the introduction of Remountable API?

### ISSUE THREAD

**Issue by andreacfm** [ruby-grape/grape#1815] opened 2018-11-08 22:58 UTC
The introduction of this commit https://github.com/ruby-grape/grape/commit/cf14fc79d0100b988fb0d5ccd9182e3135e9ae48 completely broke one of my api's.
I get any possible erro from `guess_for_anonymous` when autoloading modules to missing methods from included module.

My API is mounted as:

```
# api_base.rb
class ApiBase < Grape::API
   mount InternalApi::Base
end

# internal_api/base.rb
module InternalApi
    class Base < Grape::API
        mount InternalApi::V1::Base
        mount InternalApi::V2::Base
....


# Then InternalApi::V1::Base and InternalApi::V2::Base mount the final api files
```

One of the error I get (undefined method paginate) from:

```
module InternalApi
    module V1 
      class Base
          version :v2
           include Grape::Kaminari
           paginate per_page: 30, max_per_page: 200  
```

Is this expected and does exists an upgrade guide?

**Comment by dblock** [comment] 2018-11-09 01:11
Thanks for trying HEAD out @andreacfm, cc: @myxoh, related to #1803.

It would be helpful to get a spec that can reproduce this, let's fix it or document a workaround before release.

**Comment by andreacfm** [comment] 2018-11-09 08:57
@dblock here a spec to show the failing in including modules.
https://github.com/ruby-grape/grape/pull/1816

**Comment by myxoh** [comment] 2018-11-09 16:30
Hi, I'm going to be looking at the issues caused by the PR now. Sorry, it's been a very heptic week for me

**Comment by rromanchuk** [comment] 2018-11-12 04:04
I haven't spent any time investigation besides just reverting, just sharing what I know

```
/dependencies.rb:203:in `guess_for_anonymous': SlackBot cannot be autoloaded from an anonymous class or module (NameError)
```
in application.rb
`config.autoload_paths << "#{Rails.root}/lib"`

Location of module
`lib/slack_bot.rb`

Somewhere inside `Grape::API`

`include SlackBot`

**Comment by myxoh** [comment] 2018-11-12 10:08
@rromanchuk I couldn't reproduce that on Rails 5.2. I'll try on 4.2. Perhaps you could answer a couple of questions for me?
Which Rails version are you using?
How are you loading the API?
Is the errors happening on load time or run time?

**Comment by myxoh** [comment] 2018-11-12 10:13
@andreacfm I also was't able to reproduce autoloading issues adding `helpers V1Helpers` where `V1Helpers` is a module of helpers. It seemed to work just fine

**Comment by myxoh** [comment] 2018-11-12 10:36
I couldn't reproduce on 4.2 either. It seems that my test case is not triggering the issue. I need more information to be able to help unfortunately

**Comment by andreacfm** [comment] 2018-11-12 13:00
@myxoh 

* using Rails 4.2.10
* api is mounted as per docs in routes.rb ```mount ApiBase => '/'```
* error fires on load

I will try to reproduce the error I get with the helpers in a spec. I have already submitted the error I get using include.

**Comment by andreacfm** [comment] 2018-11-12 13:02
@myxoh autoloading errors are scary. Are you sure that the ```remountable```  implementation worth the pain?

**Comment by myxoh** [comment] 2018-11-12 14:43
If you can post a sample git repo, I can work from that. While they are scary, they are not un-solvable. I want to at least give it a go.
I do believe `remountable` is worth the trouble, and I couldn't think of any other implementation that would make this faster. This is a very core change to the way things work, so things were bound to be somewhat broken. 
The alternative was my first choice, having a separate set of APIs just for the remountable feature, but the issue with that is that they will always have second-class support. 
No alternative is particularly attractive right now, but the feature I feel is a real must on grape.

**Comment by andreacfm** [comment] 2018-11-12 15:05
@myxoh make sense. I will have something for you asap.

**Comment by dblock** [comment] 2018-11-12 16:21
I agree, we definitely want remountable. Lets fix the bugs and move forward!

**Comment by andreacfm** [comment] 2018-11-12 23:31
@myxoh sorry but I could not find the time to put together a test app. I will try by tomorrow ... busy days ... you know :)

**Comment by myxoh** [comment] 2018-11-13 13:58
Hi @rromanchuk . I've used your example as a basis for: https://github.com/myxoh/testing-grape
Could you try and make that project fail and raise a PR against it? Or anything that could help me get anything to fail

**Comment by myxoh** [comment] 2018-11-13 16:35
Wait @rromanchuk is your issue happening on grape 1.1???
If that's the case I think you have a different one, very likely not even related to grape at all!

**Comment by rromanchuk** [comment] 2018-11-13 19:30
@myxoh sorry, that was misleading, you should throw that information out, that's what is on production right now.  I only meant to share to give you context of potential troublesome gems. The issue started when i updated to the latest release against this github branch

**Comment by andreacfm** [comment] 2018-11-13 22:41
@myxoh same for me. The issue appears when using a codebase that runs fine  with grape 1.1 on the last master.

**Comment by myxoh** [comment] 2018-11-19 02:16
@andreacfm , @rromanchuk I'm still waiting on any code that replicates the issue: please 😄 ? I've linked to a blank project use `master` on grape and the autoloader which has no issues. And I've tried using `master` on a large project I'm working on, also without issues. 
I'm not sure what I'm doing differently from you, I need any blank rails project (or a PR to my project), or some more information that can help me fix the problem so that we can release

**Comment by rromanchuk** [comment] 2018-11-20 04:50
@myxoh I'll give this a go tomorrow

**Comment by myxoh** [comment] 2018-11-23 10:41
@rromanchuk, @andreacfm any luck?

**Comment by myxoh** [comment] 2018-11-23 12:06
I finally was able to reproduce the issue by including the gem Kaminari Grape. Will try to solve it now

**Comment by myxoh** [comment] 2018-11-23 12:21
Found the issue :smile:, creating a PR

**Comment by myxoh** [comment] 2018-11-23 12:35
@dblock if you are happy with that change, let's merge it. Afterwards could @rromanchuk  and @andreacfm test on your projects?

Let's get this over the line :trophy:

**Comment by dblock** [comment] 2018-11-23 14:43
Closed via https://github.com/ruby-grape/grape/pull/1823

Please give HEAD a try.

**Closed by dblock** 2018-11-23 14:43 UTC
Labels: bug?

**Comment by andreacfm** [comment] 2018-11-23 15:43
@dblock @myxoh I have a new error. In one of my code base I was injecting some helper class method reopening Grape::API.

```
Grape::API.class_eval do
 include ....
end
```

The methods are not available anymore in my api classes that extend Grape::API. Is this an expected behaviour?

**Comment by andreacfm** [comment] 2018-11-24 21:44
@myxoh works for me now. Thanks. Any idea of when this will be released?
