### ISSUE TITLE
Feature Request: disallow undeclared params

### ISSUE THREAD

**Issue by jlfaber** [ruby-grape/grape#1603] opened 2017-03-27 21:26 UTC
I know I can use `declared` to filter out undeclared params, but there are some times when I'd prefer to fail explicitly.  One example might be to help an API user who misspells the name of an optional parameter.  As currently implemented validation will succeed, but I'd much rather have it fail to clue in the user that something is amiss.

**Comment by dblock** [comment] 2017-03-28 11:47
This is a duplicate of https://github.com/ruby-grape/grape/issues/810. Would love a PR for this, it has been a long outstanding request.

**Closed by dblock** 2017-03-28 11:47 UTC
