### ISSUE TITLE
Params block only applies to immediately following endpoint

### ISSUE THREAD

**Issue by griest024** [ruby-grape/grape#1861] opened 2019-02-07 00:48 UTC
The [README](https://github.com/ruby-grape/grape#namespace-validation-and-coercion) states:
```
Namespaces allow parameter definitions and apply to every method within the namespace.
```

Maybe this is working as expected but the docs are not super clear about to which endpoints the `params` block applies.

```ruby
namespace :foo do
  params do
    requires :test
  end

  post do
    declared(params)
  end

  post :bar do
    declared(params)
  end
end
```

# Expected

### Request

`curl -X POST -H "Content-Type: application/json" localhost:9292/api/foo -d '{"test": "hi"}'`

### Response

`{"test":"hi"}`

### Request

`curl -X POST -H "Content-Type: application/json" localhost:9292/api/foo/bar -d '{"test": "hi"}'`

### Response

`{"test":"hi"}`

# Actual

### Request

`curl -X POST -H "Content-Type: application/json" localhost:9292/api/foo -d '{"test": "hi"}'`

### Response

`{"test":"hi"}`

### Request

`curl -X POST -H "Content-Type: application/json" localhost:9292/api/foo/bar -d '{"test": "hi"}'`

### Response

`{}`

Is this the correct behavior?

Possibly related to #1842

**Comment by dm1try** [comment] 2019-02-07 10:59
> Params block only applies to immediately following endpoint

AFAIK, this is how it works by default and this should be true for namespaces also: params block only applies to the immediately following namespace(to prevent ambiguity that mentioned above). 

```ruby
  params do
    requires :user_id, type: Integer, desc: 'A user ID.'
  end
  namespace ':user_id' do
    desc "Retrieve a user's status."
   ...
```

**Comment by dblock** [comment] 2019-02-07 16:05
Confirmed by design. We can't have it both ways, so I think we'll leave it as is. Closing.

**Closed by dblock** 2019-02-07 16:05 UTC
