### ISSUE TITLE
Error response returns invalid fields differently in 0.11

### ISSUE THREAD

**Issue by udiudi** [ruby-grape/grape#1010] opened 2015-05-05 09:29 UTC
Hi

I've upgraded grape 0.7 to 0.11.

My exceptions change from
``ruby
{"status":400,"message":"board_id is invalid","errors":{"board_id":["is invalid"]}}
``

to 
``ruby
{"status":400,"message":"board_id is invalid","errors":{"[\"board_id\"]":["is invalid"]}}
``

Note the board_id in errors field.

Any idea what causes it? how I can change it back to what it was?

Thanks

**Comment by dblock** [comment] 2015-05-05 14:57
Looks like a bug to me, care to write a test that reproduces this?

**Comment by udiudi** [comment] 2015-05-05 14:58
Kinda new to this, could you explain what you need?

**Comment by dblock** [comment] 2015-05-05 15:13
See https://github.com/intridea/grape/blob/master/CONTRIBUTING.md. You'll find tests for the contents of the `errors` part, write an RSpec test that reproduces what you're describing, make a pull request with just the test. It's possible that this is by design, but I am not sure why we would design it this way.

**Comment by dm1try** [comment] 2015-06-09 18:59
@udiudi, do you need some help? The validator in your example is custom one?

See upgrading notes [1](https://github.com/intridea/grape/blob/master/UPGRADING.md#changes-to-custom-validators), [2](https://github.com/intridea/grape/blob/master/UPGRADING.md#changes-to-raising-grapeexceptionsvalidation)

**Comment by dblock** [comment] 2015-08-19 17:41
So do we think it's a bug? I am inclined to close this, @dm1try what do you think? Bump @udiudi.

**Comment by dm1try** [comment] 2015-08-20 03:31
@udiudi  Unfortunately we can't do anything if we don't know how to reproduce the problem. That said, I'm closing this issue but let us know if you get a way to reproduce it. Also feel free to update `UPGRADING.md` if some step was missed.

**Closed by dm1try** 2015-08-20 03:31 UTC
Labels: bug?
