### ISSUE TITLE
Context around array validation failures

### ISSUE THREAD

**Issue by lukestephenson** [ruby-grape/grape#1131] opened 2015-08-27 04:55 UTC
Given a request like:
```
{ "orders": [ {customerId: 'invalid', salesPersonId: 5}, {customerId: 5, salesPersonId: 'invalid'} ] }
```
And the following parameter definitions:
```
    params do
      requires :orders, type: Array do
        requires :customerId, type: Integer
        requires :salesPersonId, type: Integer
      end
    end
```

Grape correctly detects that the input is invalid.  However there is no context in the errors collection about which item in the array was invalid.  Currently the error is reported against the key `orders[customerId]` but I need to be able to pair the errors back to the original element in the array like `orders[0][customerId]`.

Is this supported by grape?

**Comment by dblock** [comment] 2015-08-27 14:41
Grape doesn't provide array index context, and I think it should. Labelling this as a feature request.

**Comment by towanda** [comment] 2015-12-07 07:36
@dblock could we close this issue, since It's already implemented? Thanks.

**Closed** 2015-12-07 08:42 UTC
Labels: feature request

**Comment by dblock** [comment] 2015-12-07 11:51
:+1:

**Comment by akeuk** [comment] 2015-12-10 07:43
In Grape version 0.14.1, Array index context only return `[0]`

#### Parameter definitions:

```ruby
params do
  requires :employees, type: Array do
    requires :name, type: String
    requires :email, regexp: /.+@.+/
  end
end
```

#### 1. Failure in _first_ element

Request (invalid email):

```javascript
{
  "employees": [
    {
      "name": "Jovani Kiehn",
      "email": "invalid_email"
    },
    {
      "name": "Eliezer Torphy",
      "email": "eliezer_torphy@gmail.com"
    }
  ]
}
```

Response:

```javascript
employees[0][email] is invalid
```

#### 2. Failure in _second_ element

Request (missing name):

```javascript
{
  "employees": [
    {
      "name": "Jovani Kiehn",
      "email": "jovani_kiehn@yahoo.com"
    },
    {
       "email": "eliezer_torphy@gmail.com"
    }
  ]
}
```

Response:

```javascript
employees[0][name] is missing
```

Thanks!

**Comment by towanda** [comment] 2015-12-10 08:50
@akeuk I'll take a look tonight, thanks!

**Comment by akeuk** [comment] 2015-12-22 02:25
@towanda Thank you! :)

How was it now?

**Comment by galkon** [comment] 2016-03-09 05:55
With this change now Hashes also return indexes so if for example I have
`
params do
  requires :employees, type: Hash do
    requires :name, type: String
    requires :email, type: Hash
  end
end
`

I would expect `employess[name] is missing, employees[email] is missing` not `employess[0][name] is missing, employees[0][email] is missing` currently it returns `employess[0][name] is missing, employees[0][email] is missing`

**Comment by dblock** [comment] 2016-03-09 16:44
That would be a bug, did I overlook this? Definitely would be a regression, appreciate at least a spec for this.

**Comment by galkon** [comment] 2016-03-09 20:36
Sure, I'll whip something up when I get into work.

**Comment by galkon** [comment] 2016-03-10 00:23
Wrote another test that seems to be failing around testing arrays with multiple failures: https://github.com/ruby-grape/grape/pull/1314 does this seem right?

**Comment by akeuk** [comment] 2016-07-07 05:32
@dblock What is your plan on this feature?

Thank you.

**Comment by dblock** [comment] 2016-07-07 15:40
You mean fixing #1313 @akeuk ?

**Comment by akeuk** [comment] 2016-07-07 16:04
@dblock Yes.

**Comment by dblock** [comment] 2016-07-07 16:59
I am not working on it. Please contribute.
