### ISSUE TITLE
How do I respond to stream results via API - Grape

### ISSUE THREAD

**Issue by datpmt** [ruby-grape/grape#2367] opened 2023-11-07 03:27 UTC
Recently I have been using the ChatGPT API and I've found a very useful method of sending information called streaming. Instead of sending a long piece of text all at once, ChatGPT sends it in small chunks until it's finished. For example, the text "Hello! How can I assist you today?" would be divided as follows:
0.1s: Hello
0.2s: !
0.3s: How
...
0.9s: today
1s: ?
Thank you for everyone's contributions!

```ruby
# /api/v1/chat_gpt
module API
  module V1
    class AttachmentStream
      attr_reader :response
      def initialize(response)
        @response = response
      end

      def each
        yield response.read_body
      end
    end
    class ChatGpt < Grape::API
      helpers API::V1::Helpers::Authentication
      helpers API::V1::Helpers::ChatGpt
      resource :chat_gpt do
        desc 'Chat with ChatGPT'
        params do
          use :authorization_token
          requires :messages, type: Array[Hash], desc: 'Chat Content'
          optional :max_tokens, type: Integer
          optional :stream, type: Boolean, default: false
        end
        post do
          content_type 'text/event-stream'
          url = 'https://api.openai.com/v1/chat/completions'
          uri = URI(url)

          data = {
            model: 'gpt-3.5-turbo',
            stream: true,
            messages: [
              {
                  "role": "user",
                  "content": "hi"
              }
            ]
          }

          Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
            request = Net::HTTP::Post.new(uri.path)

            # Set any request headers if required
            request['Content-Type'] = 'application/json'
            request['Authorization'] = "Bearer #{ENV.fetch('GPT_KEY')}"
            # Set the request body if required
            request.body = data.to_json

            http.request(request) do |response|
              stream AttachmentStream.new(response)
            end
          end
        end
      end
    end
  end
end
```
- They seem to be returning at the same time :<
![image](https://github.com/ruby-grape/grape/assets/76593070/4d3ad27c-f2de-464b-9f47-6682e607a77c)
- Via OPENAI
![image](https://github.com/ruby-grape/grape/assets/76593070/05395d0c-1f5a-4329-a114-0e320b5cc769)

**Comment by dblock** [comment] 2023-11-07 15:14
Can you please elaborate a little? I am not sure what "respond to stream results" means. Are you trying to do something on the server or client?

**Comment by datpmt** [comment] 2023-11-07 15:20
I want the results returned from my API to be the same as the results returned from OpenAI.
The first screenshot is the return from my API. And it is returning at the same time, not sequentially until the end of the transfer process like OpenAI (2nd screenshot). I have researched many articles about streaming but I haven't found any that can help me complete it. Thank you for your interest!

**Comment by dblock** [comment] 2023-11-07 15:35
I see. Start by doing this without Grape. 

Does `Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|` actually consume responses in parallel? According to  https://stackoverflow.com/questions/35495016/stream-the-response-body-of-an-http-get-to-an-http-post-with-ruby it may not. Start by showing code that is 100% performing a streaming request/response with OpenAPI in Ruby, then we can figure out how Grape should respond without collecting that data as a stream as well.

**Comment by datpmt** [comment] 2023-11-08 01:46
hi @dblock 
I'm sure about `Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|` actually consuming responses in parallel. According to https://stackoverflow.com/questions/41306082/ruby-nethttp-read-the-header-before-the-body-without-head-request 
> net/http supports streaming, you can use this to read the header before the body.

But I haven't seen any article saying it can respond to streaming endpoint so I need your help.

**Comment by datpmt** [comment] 2023-11-08 03:38
And Grape `Readme.md` has this one:
![image](https://github.com/ruby-grape/grape/assets/76593070/b2894969-e745-4a98-8738-034377800ad5)

But it also seems to return at the same time, I don't know what to do it returns one piece every second

**Comment by dblock** [comment] 2023-11-08 17:17
> I'm sure about `Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|` actually consuming responses in parallel.

Care to show a working example with OpenAPI in pure ruby?

> But it also seems to return at the same time, I don't know what to do it returns one piece every second

I don't know either. Let's figure it out. Looks like @urkle contributed much of the streaming implementation in https://github.com/ruby-grape/grape/pull/1520, maybe he is around to help?

**Comment by dblock** [comment] 2023-11-08 18:21
I know what the problem is @datpmt - what web server are you using? I got it working with Puma, but not Webrick.
I have a working sample in https://github.com/ruby-grape/grape-on-rack/pull/56.

![stream](https://github.com/ruby-grape/grape/assets/542335/c9306d29-7d8e-4ce5-a718-43491ce796c5)

Let us know if this helps?

**Comment by datpmt** [comment] 2023-11-09 06:57
Thank you for your help @dblock !
I use `Puma` too and I work with the Rails app (~> 6.1.5) not using either `rack` or `rackup`

When I create the new file `test.rb` (code bellow) and start the server by command line:
```bash
ruby test.rb
```

```ruby
# test.rb
require 'grape'
require 'rack'
require 'rack/handler/puma'

class MyStream
  def each
    3.times do
      yield "data: #{{ time: Time.now }.to_json}\n\n"
      sleep 1
    end
  end
end

class ChatGpt < Grape::API
  resource :chat_gpt do
    get do
      stream MyStream.new
      content_type 'text/event-stream'
      status 200
    end
  end
end

Rack::Handler::Puma.run ChatGpt.new

```
It working well

https://github.com/ruby-grape/grape/assets/76593070/15c1f20b-84b4-4fe0-8405-fed68638e1d8

But when I start my main project (with Rails app) by command line:
```bash
rails s -p 3005
```
Code in my Rails app:
```ruby
# /api/v1/chat_gpt
module API
  module V1
    class MyStream
      def each
        3.times do
          yield "data: #{{ time: Time.zone.now }.to_json}\n\n"
          sleep 1
        end
      end
    end

    class ChatGpt < Grape::API
      resource :chat_gpt do
        get do
          stream MyStream.new
          content_type 'text/event-stream'
          status 200
        end
      end
    end
  end
end

```
There seems to be no difference. I tried adding `gem 'rack'` to my `Gemfile` without success.


https://github.com/ruby-grape/grape/assets/76593070/67f23bca-dd1b-4770-b748-5c90c7d0472d

I think the problem is related to `Rails` or `Rack`, do you have any ideas?
Thank you again for your interest!

**Comment by dblock** [comment] 2023-11-09 15:35
Let's try to isolate it. Care to port my sample that I added in https://github.com/ruby-grape/grape-on-rack/pull/56 to https://github.com/ruby-grape/grape-on-rails? Make a (non-working) PR?

**Comment by datpmt** [comment] 2023-11-09 15:42
hi @dblock 
If you have time, I need the sample at https://github.com/ruby-grape/grape-on-rails
Thank you again for your interest!

**Comment by dblock** [comment] 2023-11-09 15:46
> If you have time, I need the sample at https://github.com/ruby-grape/grape-on-rails

I do not, but you should find time to write and, and I will dig into why it doesn't work

**Comment by dblock** [comment] 2023-11-10 00:07
I am going to close the issue here since it's clearly not a Grape problem, as grape returns all the right things per spec and works on Puma.

**Closed by dblock** 2023-11-10 00:07 UTC
Labels: bug?, question

**Comment by datpmt** [comment] 2023-11-10 02:47
According to https://github.com/rails/rails/issues/38780#issuecomment-601930546, this is not a Rails problem but an inconsistent Rack version.

**Comment by dblock** [comment] 2023-11-10 06:06
Did upgrading Rack to >2.2 or <=2.1 fix it in your application?

**Comment by datpmt** [comment] 2023-11-10 06:47
> Did upgrading Rack to >2.2 or <=2.1 fix it in your application?

Downgrade `rack (2.2.4)` to `rack (2.1.4.3)` it works fine!

**Comment by trialize** [comment] 2024-10-15 19:20
Any plans to migrate to rack 3?
Streams are effectively dead in 2.2+ (tested on 2.2.8, 2.2.9, 2.2.10)

Example:

```ruby
require 'grape'
require 'openai'


class StreamAPI < Grape::API
  format :txt

  helpers do
    def openai_client
      @openai_client ||= OpenAI::Client.new(access_token: ENV['OPENAI_API_KEY'])
    end
  end

  resource :stream do
    get do
      prompt =  "Describe a character called Anna!"


      header 'content-type', 'text/event-stream'
      header 'cache-control', 'no-cache'
      header 'connection', 'keep-alive'

      env['api.format'] = :binary

      status 200

      stream_body = Enumerator.new do |yielder|
        stream_proc = proc do |chunk, _bytesize|
          content = chunk.dig("choices", 0, "delta", "content")
          yielder << content if content
        end

        begin
          openai_client.chat(
            parameters: {
              model: 'gpt-3.5-turbo',
              messages: [{ role: 'user', content: prompt }],
              temperature: 0.7,
              stream: stream_proc
            }
          )

          # Indicate the end of the stream
          yielder << "\n\nDONE"
          
          env['rack.hijack'].call if env['rack.hijack']
        rescue => e
          yielder << "Event: error\nData: #{e.message}\n\n"
        end
      end

      stream stream_body

    end
  end
end
```

**Comment by trialize** [comment] 2024-10-15 19:57
@datpmt The Issue is with Rack:ETag middleware.

**Comment by dblock** [comment] 2024-10-15 22:57
@trialize got a link to a bug open/closed? to be clear, Grape supports Rack 3.0, we even have [integration tests](https://github.com/ruby-grape/grape/tree/master/spec/integration/rack_3_0) for specifics.

**Comment by trialize** [comment] 2024-10-16 11:51
@dblock 

https://github.com/rack/rack/issues/1628 (2.x -> still the issue, could share the code)
Additionally here: https://github.com/rack/rack/issues/1619

Quick solution for Rails+Grape combo is to put `config.middleware.delete Rack::ETag` in `config/application.rb`
(Unless you specifically need etags).

Re: Grape on Rack3 - Can confirm: it works in practice, no visible issues. The only thing, I'd advice to put a line in README to highlight this.

**Comment by dblock** [comment] 2024-10-16 13:39
> [rack/rack#1628](https://github.com/rack/rack/issues/1628) (2.x -> still the issue, could share the code) Additionally here: [rack/rack#1619](https://github.com/rack/rack/issues/1619)
> 
> Quick solution for Rails+Grape combo is to put `config.middleware.delete Rack::ETag` in `config/application.rb` (Unless you specifically need etags).

Add a 2.x spec with your repro similar to https://github.com/ruby-grape/grape/tree/master/spec/integration/rack_3_0 in which you `config.middleware.delete Rack::ETag` with a comment to the Rack issue?

> Re: Grape on Rack3 - Can confirm: it works in practice, no visible issues. The only thing, I'd advice to put a line in README to highlight this.

Double check that we have a spec like the one above in https://github.com/ruby-grape/grape/tree/master/spec/integration/rack_3_0 or add one, along with the README suggestion, that would be helpful.
