### ISSUE TITLE
Array failing on single non-array value.

### ISSUE THREAD

**Issue by ZeroInputCtrl** [ruby-grape/grape#2028] opened 2020-03-23 16:36 UTC
Version 1.2.3 and earlier one could pass in a single value and grape would auto transform (coerce?) it to an array.
If you had an endpoint with this:
```
params do
  optional :stuff, type: Array[String]
end
get '/' { present: :ok }
```
And decided to called it like this:
```
get '/', params: { stuff: "hello" }
# or
get '/', params: { stuff: ["hello"] }
```
They would both work no problem.
Now (version 1.3.1) if you do the above grape will return `stuff is invalid`

If this change was not intentional i can create a spec for it (and maybe fix if i have time). But if it is intentional i guess the Upgrading doc should be updated?

**Comment by dblock** [comment] 2020-03-23 18:31
This is https://github.com/ruby-grape/grape/blob/master/UPGRADING.md#ensure-that-array-types-have-explicit-coercions. If it's not clear, please do contribute to the doc! Also do run a spell checker on it while you're at it ;)

**Comment by dblock** [comment] 2020-03-23 18:31
I'll close the issue since it's by design.

**Closed by dblock** 2020-03-23 18:31 UTC
Labels: bug?
